In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/amazon/amazon_reviews.csv

In [2]:
#for data wrangling and manipulation

import pandas as pd
import numpy as np

#for NLP text processing and formatting

import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# For word lemmitization
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer 
# for word Stemming
nltk.download('omw-1.4')
from nltk.stem.porter import PorterStemmer

# for Machine Learning process

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedShuffleSplit

# for Machine Learning model evaluation

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Global Parameters
stop_words = set(stopwords.words('english'))

from wordcloud import WordCloud

import matplotlib.pyplot as plt
%matplotlib inline

# from autosklearn.regression import AutoSklearnRegressor

import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode, iplot#for data wrangling and manipulation

import pandas as pd
import numpy as np

#for NLP text processing and formatting

import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# For word lemmitization
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer 
# for word Stemming
nltk.download('omw-1.4')
from nltk.stem.porter import PorterStemmer

# for Machine Learning process

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedShuffleSplit

# for Machine Learning model evaluation

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Global Parameters
stop_words = set(stopwords.words('english'))

from wordcloud import WordCloud

import matplotlib.pyplot as plt
%matplotlib inline

# from autosklearn.regression import AutoSklearnRegressor

import plotly.graph_objs as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode, iplot

[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [3]:
df = pd.read_csv("../input/amazon/amazon_reviews.csv")

In [4]:
df.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
0,0,NaN,4.0,No issues.,2014-07-23,138,0,0,0,0,0.0,0.0
1,1,0mie,5.0,"Purchased this for my device, it worked as adv...",2013-10-25,409,0,0,0,0,0.0,0.0
2,2,1K3,4.0,it works as expected. I should have sprung for...,2012-12-23,715,0,0,0,0,0.0,0.0
3,3,1m2,5.0,This think has worked out great.Had a diff. br...,2013-11-21,382,0,0,0,0,0.0,0.0
4,4,2&amp;1/2Men,5.0,"Bought it with Retail Packaging, arrived legit...",2013-07-13,513,0,0,0,0,0.0,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            4915 non-null   int64
 1   reviewerName          4914 non-null   object
 2   overall               4915 non-null   float64
 3   reviewText            4914 non-null   object
 4   reviewTime            4915 non-null   object
 5   day_diff              4915 non-null   int64
 6   helpful_yes           4915 non-null   int64
 7   helpful_no            4915 non-null   int64
 8   total_vote            4915 non-null   int64
 9   score_pos_neg_diff    4915 non-null   int64
 10  score_average_rating  4915 non-null   float64
 11  wilson_lower_bound    4915 non-null   float64
dtypes: float64(3), int64(6), object(3)
memory usage: 460.9+ KB

In [6]:
df.describe()

,Unnamed: 0,overall,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
count,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000,4915.000000
mean,2457.000000,4.587589,437.367040,1.311089,0.210376,1.521465,1.100712,0.075468,0.020053
std,1418.982617,0.996845,209.439871,41.619161,4.023296,44.123095,39.367949,0.256062,0.077187
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,-130.000000,0.000000,0.000000
25%,1228.500000,5.000000,281.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2457.000000,5.000000,431.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3685.500000,5.000000,601.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,4914.000000,5.000000,1064.000000,1952.000000,183.000000,2020.000000,1884.000000,1.000000,0.957544

In [7]:
df.isnull().any()

Unnamed: 0              False
reviewerName             True
overall                 False
reviewText               True
reviewTime              False
day_diff                False
helpful_yes             False
helpful_no              False
total_vote              False
score_pos_neg_diff      False
score_average_rating    False
wilson_lower_bound      False
dtype: bool

In [8]:
df.dropna(inplace = True)
df.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
1,1,0mie,5.0,"Purchased this for my device, it worked as adv...",2013-10-25,409,0,0,0,0,0.0,0.0
2,2,1K3,4.0,it works as expected. I should have sprung for...,2012-12-23,715,0,0,0,0,0.0,0.0
3,3,1m2,5.0,This think has worked out great.Had a diff. br...,2013-11-21,382,0,0,0,0,0.0,0.0
4,4,2&amp;1/2Men,5.0,"Bought it with Retail Packaging, arrived legit...",2013-07-13,513,0,0,0,0,0.0,0.0
5,5,2Cents!,5.0,It's mini storage. It doesn't do anything els...,2013-04-29,588,0,0,0,0,0.0,0.0

In [9]:
df.count()

Unnamed: 0              4913
reviewerName            4913
overall                 4913
reviewText              4913
reviewTime              4913
day_diff                4913
helpful_yes             4913
helpful_no              4913
total_vote              4913
score_pos_neg_diff      4913
score_average_rating    4913
wilson_lower_bound      4913
dtype: int64

In [10]:
print("Before {}".format(len(df)))
dataAfter = df.dropna(subset=["overall"]) # removes all NAN in reviews.rating
print("After {}".format(len(dataAfter)))
dataAfter["overall"] = dataAfter["overall"].astype(int)

Before 4913
After 4913

In [11]:
split = StratifiedShuffleSplit(n_splits=5, test_size=0.2)
for train_index, test_index in split.split(dataAfter, dataAfter["overall"]): 
    start_train = dataAfter.reindex(train_index)
    start_test = dataAfter.reindex(test_index)

In [12]:
reviews = start_train.copy()
reviews.head()

,Unnamed: 0,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
4120,4120.0,"Sean Tomlinson ""Sean T""",5.0,"What is there to say? It's a nice big, cheap, ...",2014-06-23,168.0,0.0,0.0,0.0,0.0,0.0,0.0
4402,4402.0,Tactical Keychains,5.0,Works perfect in my Galaxy Tab 4,2014-06-07,184.0,0.0,0.0,0.0,0.0,0.0,0.0
3320,3320.0,Mr.Incognito,4.0,"Great MicroSD, fast and holds a ton of memory....",2014-06-21,170.0,0.0,0.0,0.0,0.0,0.0,0.0
118,118.0,ALBERTO MENDOZA ALVAREZ,5.0,"Love it, good quality good performance, great ...",2014-10-01,68.0,0.0,0.0,0.0,0.0,0.0,0.0
2800,2800.0,Lazer G.,5.0,"Not much to say about this, but it was definit...",2014-01-02,340.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
corr_matrix = reviews.corr()
corr_matrix

,Unnamed: 0,overall,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
Unnamed: 0,1.000000,-0.011463,-0.002937,0.011073,0.013743,0.011697,0.010304,-0.007877,-0.001792
overall,-0.011463,1.000000,-0.091862,-0.034410,-0.066289,-0.038496,-0.029610,-0.151872,-0.134134
day_diff,-0.002937,-0.091862,1.000000,0.042296,0.030083,0.042637,0.041643,0.130900,0.140871
helpful_yes,0.011073,-0.034410,0.042296,1.000000,0.593178,0.997308,0.996617,0.112519,0.358568
helpful_no,0.013743,-0.066289,0.030083,0.593178,1.000000,0.650619,0.525004,0.090862,0.288412
total_vote,0.011697,-0.038496,0.042637,0.997308,0.650619,1.000000,0.987907,0.114413,0.364500
score_pos_neg_diff,0.010304,-0.029610,0.041643,0.996617,0.525004,0.987907,1.000000,0.109677,0.349626
score_average_rating,-0.007877,-0.151872,0.130900,0.112519,0.090862,0.114413,0.109677,1.000000,0.865014
wilson_lower_bound,-0.001792,-0.134134,0.140871,0.358568,0.288412,0.364500,0.349626,0.865014,1.000000

In [14]:
# splitting ratings from 1-5 into positive, neutral, and negative
def sentiments(rating):
    if (rating == 5) or (rating == 4):
        return "Positive"
    elif rating == 3:
        return "Neutral"
    elif (rating == 2) or (rating == 1) or (rating == 0):
        return "Negative"
# Add sentiments to the data
start_train["Sentiment"] = start_train["overall"].apply(sentiments)
start_test["Sentiment"] = start_test["overall"].apply(sentiments)
start_train["Sentiment"][:20]

4120    Positive
4402    Positive
3320    Positive
118     Positive
2800    Positive
1237    Positive
2813    Positive
1643    Positive
4843    Positive
1748    Positive
3160    Positive
4451    Positive
476     Positive
4041    Positive
1046    Positive
2931    Positive
258     Positive
2453    Positive
224     Positive
2053    Positive
Name: Sentiment, dtype: object

In [15]:
review=df[['reviewText','overall']]
review.head()

                                          reviewText  overall
1  Purchased this for my device, it worked as adv...      5.0
2  it works as expected. I should have sprung for...      4.0
3  This think has worked out great.Had a diff. br...      5.0
4  Bought it with Retail Packaging, arrived legit...      5.0
5  It's mini storage.  It doesn't do anything els...      5.0

In [16]:
round(review.isnull().sum().sort_values(ascending=False)*100/len(review),2)

reviewText    0.0
overall       0.0
dtype: float64

In [17]:
review=review.dropna()
review.head()

                                          reviewText  overall
1  Purchased this for my device, it worked as adv...      5.0
2  it works as expected. I should have sprung for...      4.0
3  This think has worked out great.Had a diff. br...      5.0
4  Bought it with Retail Packaging, arrived legit...      5.0
5  It's mini storage.  It doesn't do anything els...      5.0

In [18]:
review['encoded_cat'] = review.overall.astype('category').cat.codes
review.head()

                                          reviewText  overall  encoded_cat
1  Purchased this for my device, it worked as adv...      5.0            4
2  it works as expected. I should have sprung for...      4.0            3
3  This think has worked out great.Had a diff. br...      5.0            4
4  Bought it with Retail Packaging, arrived legit...      5.0            4
5  It's mini storage.  It doesn't do anything els...      5.0            4

In [19]:
def preprocess_review_text(review):
    """
    Function to process the the review text and transform it into format usable by Machine learning models
    """
    
    # to convert all the characters of the review into lower case alphabets
    review.lower()
    
    # Remove urls from the reviews
    review = re.sub(r"http\S+|www\S+|https\S+", '', review, flags=re.MULTILINE)
    
    # Remove user related references from the reviews:: '@' and '#' 
    review = re.sub(r'\@\w+|\#','', review)
    
    # Remove punctuations from the reviews
    review = review.translate(str.maketrans('', '', string.punctuation))
    
    # Remove stopwords from the reviews
    review_tokens = word_tokenize(review)
    filtered_words = [w for w in review_tokens if not w in stop_words]
    joined_text = " ".join(filtered_words)
    
    return joined_text

In [20]:
def get_feature_vector(train_fit):
    """
    Function to Convert a collection of raw documents to a matrix of TF-IDF features.
    TF-IDF - Term Frequency Inverse Documnet Frequency
    """
    
    vector = TfidfVectorizer(sublinear_tf=True)      # Defining the vector
    vector.fit(train_fit)                            # fitting the data into the vector
    return vector                                    # returning the vector as function call|

In [21]:
processed_text = df['reviewText'].apply(preprocess_review_text)

print("Processed text :: \n\n", processed_text)

Processed text ::

 1       Purchased device worked advertised You never m...
2       works expected I sprung higher capacity I thin...
3       This think worked greatHad diff bran 64gb card...
4       Bought Retail Packaging arrived legit orange e...
5       Its mini storage It doesnt anything else suppo...
                              ...
4910    I bought Sandisk 16GB Class 10 use HTC Inspire...
4911    Used extending capabilities Samsung Galaxy Not...
4912    Great card fast reliable It comes optional ada...
4913    Good amount space stuff I want fits GoPro What...
4914    Ive heard bad things 64gb Micro SD card crappi...
Name: reviewText, Length: 4913, dtype: object

In [22]:
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(i) for i in processed_text]
lemmatizer = WordNetLemmatizer()
lemma_words = [lemmatizer.lemmatize(w, pos='a') for w in stemmed_words]
tf_vector = get_feature_vector(np.array(df["reviewText"]).ravel())
X = tf_vector.transform(np.array(review["reviewText"]).ravel())     # Predictor Variable
y = np.array(review["encoded_cat"]).ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)
NB_model = MultinomialNB()

NB_model.fit(X_train, y_train)

MultinomialNB()

In [23]:
y_predict_nb = NB_model.predict(X_test)

print("Accuracy Score for Naive Bayes Model is :: ", accuracy_score(y_test, y_predict_nb))

Accuracy Score for Naive Bayes Model is ::  0.7863682604272635

In [24]:
round(df['overall'].value_counts()*100/len(df),2)
df = df.sort_values("wilson_lower_bound", ascending=False)
df.drop('Unnamed: 0', inplace = True, axis = 1)
df.head()

,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
2031,"Hyoun Kim ""Faluzure""",5.0,[[ UPDATE - 6/19/2014 ]]So my lovely wife boug...,2013-01-05,702,1952,68,2020,1884,0.966337,0.957544
3449,NLee the Engineer,5.0,I have tested dozens of SDHC and micro-SDHC ca...,2012-09-26,803,1428,77,1505,1351,0.948837,0.936519
4212,SkincareCEO,1.0,NOTE: please read the last update (scroll to ...,2013-05-08,579,1568,126,1694,1442,0.925620,0.912139
317,"Amazon Customer ""Kelly""",1.0,"If your card gets hot enough to be painful, it...",2012-02-09,1033,422,73,495,349,0.852525,0.818577
4672,Twister,5.0,Sandisk announcement of the first 128GB micro ...,2014-07-03,158,45,4,49,41,0.918367,0.808109

In [25]:
def missing_values_analysis(df):
    na_columns_ = [col for col in df.columns if df[col].isnull().sum() > 0]
    n_miss = df[na_columns_].isnull().sum().sort_values(ascending=True)
    ratio_ = (df[na_columns_].isnull().sum() / df.shape[0] * 100).sort_values(ascending=True)
    missing_df = pd.concat([n_miss, np.round(ratio_, 2)], axis=1, keys=['Total Missing Values', 'Ratio'])
    missing_df = pd.DataFrame(missing_df)
    return missing_df

def check_dataframe(df, head=5, tail = 5):
    
    print(" SHAPE ".center(82,'~'))
    print('Rows: {}'.format(df.shape[0]))
    print('Columns: {}'.format(df.shape[1]))
    print(" TYPES ".center(82,'~'))
    print(df.dtypes)
    print("".center(82,'~'))
    print(missing_values_analysis(df))
    print(' DUPLICATED VALUES '.center(83,'~'))
    print(df.duplicated().sum())
    print(" QUANTILES ".center(82,'~'))
    print(df.quantile([0, 0.05, 0.50, 0.95, 0.99, 1]).T)

check_dataframe(df)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SHAPE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rows: 4913
Columns: 11
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TYPES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
reviewerName             object
overall                 float64
reviewText               object
reviewTime               object
day_diff                  int64
helpful_yes               int64
helpful_no                int64
total_vote                int64
score_pos_neg_diff        int64
score_average_rating    float64
wilson_lower_bound      float64
dtype: object
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Empty DataFrame
Columns: [Total Missing Values, Ratio]
Index: []
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ DUPLICATED VALUES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ QUANTILES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       0.00  0.05   0.50        0.95       0.99         1.00
overall                 1.0   2.0    5.0    5.000000    5.00000     5.000000
day_diff                1.0  98.0  431.0  747.400000  943.00000  1064.000000
helpful_yes             0.0   0.0    0.0    1.000000    3.00000  1952.000000
helpful_no              0.0   0.0    0.0    0.000000    2.00000   183.000000
total_vote              0.0   0.0    0.0    1.000000    4.00000  2020.000000
score_pos_neg_diff   -130.0   0.0    0.0    1.000000    2.00000  1884.000000
score_average_rating    0.0   0.0    0.0    1.000000    1.00000     1.000000
wilson_lower_bound      0.0   0.0    0.0    0.206549    0.34238     0.957544

In [26]:
def check_class(dataframe):
    nunique_df = pd.DataFrame({'Variable': dataframe.columns,
                               'Classes': [dataframe[i].nunique() \
                                           for i in dataframe.columns]})

    nunique_df = nunique_df.sort_values('Classes', ascending=False)
    nunique_df = nunique_df.reset_index(drop = True)
    return nunique_df

check_class(df)

                Variable  Classes
0             reviewText     4912
1           reviewerName     4593
2             reviewTime      689
3               day_diff      689
4     wilson_lower_bound       40
5   score_average_rating       28
6     score_pos_neg_diff       27
7             total_vote       26
8            helpful_yes       23
9             helpful_no       17
10               overall        5

In [27]:
constraints = ['#581845','#C70039','#2E4053','#1ABC9C','#7F8C8D']

def categorical_variable_summary(df, column_name):
    fig = make_subplots(rows=1,cols=2,
                        subplot_titles=('Countplot','Percentages'),
                        specs=[[{"type": "xy"}, {'type':'domain'}]])

    fig.add_trace(go.Bar( y = df[column_name].value_counts().values.tolist(), 
                          x = [str(i) for i in df[column_name].value_counts().index], 
                          text = df[column_name].value_counts().values.tolist(),
                          textfont = dict(size=15),
                          name = column_name,
                          textposition = 'auto',
                          showlegend=False,
                          marker=dict(color = constraints,
                                      line=dict(color='#DBE6EC',
                                                width=1))),
                  row = 1, col = 1)
    
    fig.add_trace(go.Pie(labels= df[column_name].value_counts().keys(),
                         values= df[column_name].value_counts().values,
                         textfont = dict(size = 20),
                         textposition='auto',
                         showlegend = False,
                         name = column_name,
                         marker=dict(colors=constraints)),
                  row = 1, col = 2)
    
    fig.update_layout(title={'text': column_name,
                             'y':0.9,
                             'x':0.5,
                             'xanchor': 'center',
                             'yanchor': 'top'},
                      template='plotly_white')
    
    iplot(fig)

In [28]:
example_review = df.reviewText[2031]

In [29]:
example_review = re.sub("[^a-zA-Z]",' ',example_review)

In [30]:
example_review = example_review.lower().split()

In [31]:
rt = lambda x: re.sub("[^a-zA-Z]",' ',str(x))
df["reviewText"] = df["reviewText"].map(rt)
df["reviewText"] = df["reviewText"].str.lower()
df.head(10)

,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound
2031,"Hyoun Kim ""Faluzure""",5.0,update so my lovely wife boug...,2013-01-05,702,1952,68,2020,1884,0.966337,0.957544
3449,NLee the Engineer,5.0,i have tested dozens of sdhc and micro sdhc ca...,2012-09-26,803,1428,77,1505,1351,0.948837,0.936519
4212,SkincareCEO,1.0,note please read the last update scroll to ...,2013-05-08,579,1568,126,1694,1442,0.925620,0.912139
317,"Amazon Customer ""Kelly""",1.0,if your card gets hot enough to be painful it...,2012-02-09,1033,422,73,495,349,0.852525,0.818577
4672,Twister,5.0,sandisk announcement of the first gb micro ...,2014-07-03,158,45,4,49,41,0.918367,0.808109
1835,goconfigure,5.0,bought from bestbuy online the day it was anno...,2014-02-28,283,60,8,68,52,0.882353,0.784651
3981,"R. Sutton, Jr. ""RWSynergy""",5.0,the last few days i have been diligently shopp...,2012-10-22,777,112,27,139,85,0.805755,0.732136
3807,R. Heisler,3.0,i bought this card to replace a lost gig in...,2013-02-27,649,22,3,25,19,0.880000,0.700442
4306,Stellar Eller,5.0,while i got this card as a deal of the day o...,2012-09-06,823,51,14,65,37,0.784615,0.670334
4596,"Tom Henriksen ""Doggy Diner""",1.0,hi i ordered two card and they arrived the nex...,2012-09-22,807,82,27,109,55,0.752294,0.663595

In [32]:
df[['polarity', 'subjectivity']] = df['reviewText'].apply(lambda Text: pd.Series(TextBlob(Text).sentiment))

for index, row in df['reviewText'].iteritems():

    score = SentimentIntensityAnalyzer().polarity_scores(row)

    neg = score['neg']
    neu = score['neu']
    pos = score['pos']
    if neg > pos:
        df.loc[index, 'sentiment'] = "Negative"
    elif pos > neg:
        df.loc[index, 'sentiment'] = "Positive"
    else:
        df.loc[index, 'sentiment'] = "neutral"

In [33]:
df[df["sentiment"] == "Positive"].sort_values("wilson_lower_bound", ascending=False).head(5)

,reviewerName,overall,reviewText,reviewTime,day_diff,helpful_yes,helpful_no,total_vote,score_pos_neg_diff,score_average_rating,wilson_lower_bound,polarity,subjectivity,sentiment
2031,"Hyoun Kim ""Faluzure""",5.0,update so my lovely wife boug...,2013-01-05,702,1952,68,2020,1884,0.966337,0.957544,0.163859,0.562259,Positive
3449,NLee the Engineer,5.0,i have tested dozens of sdhc and micro sdhc ca...,2012-09-26,803,1428,77,1505,1351,0.948837,0.936519,0.103870,0.516435,Positive
4212,SkincareCEO,1.0,note please read the last update scroll to ...,2013-05-08,579,1568,126,1694,1442,0.925620,0.912139,0.212251,0.505394,Positive
317,"Amazon Customer ""Kelly""",1.0,if your card gets hot enough to be painful it...,2012-02-09,1033,422,73,495,349,0.852525,0.818577,0.143519,0.494207,Positive
4672,Twister,5.0,sandisk announcement of the first gb micro ...,2014-07-03,158,45,4,49,41,0.918367,0.808109,0.172332,0.511282,Positive

In [34]:
df.groupby(["sentiment"])[['overall']].mean()

            overall
sentiment
Negative   3.968051
Positive   4.737439
neutral    4.687500